/** Classification utilisée uniquement lors du seed initial. */
export const KEYWORDS = {
  geo: [
    "PAYS",
    "CAPITALE",
    "CONTINENT",
    "OCÉAN",
    "FUSEAU",
    "VILLE",
    "RÉGION",
    "EUROPE",
    "AFRIQUE",
    "ASIE",
    "AMÉRIQUE",
    "OCÉANIE",
    "DÉSERT",
    "FLEUVE",
    "MONTAGNE",
    "ÎLE",
    "LANGUE OFFICIELLE",
    "FRONTIÈRE",
  ],
  science: [
    "SYMBOLE CHIMIQUE",
    "FORMULE CHIMIQUE",
    "FORMULE DE",
    "PLANÈTE",
    "ÉLÉMENT",
    "CHIMIQUE",
    "ATOME",
    "MOLÉCULE",
    "BITS",
    "OCTET",
    "NEWTON",
    "VITESSE DE",
    "ANIMAL DE",
    "PLUS GRAND ANIMAL",
    "PLUS PETIT",
    "TEMPÉRATURE",
    "ÉNERGIE",
  ],
  sport: [
    "SPORT",
    "BALLON",
    "FOOTBALL",
    "TENNIS",
    "BASKET",
    "RUGBY",
    "OLYMP",
    "COUPE DU MONDE",
    "JOUEUR",
    "MATCH",
    "PING-PONG",
    "NATATION",
    "FORMULE 1",
    "GOLF",
  ],
  culture: [
    "PEINT",
    "PEINTRE",
    "FILM",
    "CINÉMA",
    "LIVRE",
    "AUTEUR",
    "MUSIQUE",
    "CHANSON",
    "ACTEUR",
    "RÉALISATEUR",
    "MUSÉE",
    "ŒUVRE",
    "ROMAN",
    "PRIX",
    "NOBEL",
  ],
  history: [
    "ANNÉE",
    "SIÈCLE",
    "GUERRE",
    "RÉVOLUTION",
    "EMPIRE",
    "ROI",
    "REINE",
    "PRÉSIDENT",
    "INDÉPENDANCE",
    "PREMIÈRE GUERRE",
    "DEUXIÈME GUERRE",
    "MOYEN ÂGE",
    "ANTIQUE",
  ],
};

export function detectCategory(questionText) {
  const text = questionText.toUpperCase();
  for (const [categoryId, words] of Object.entries(KEYWORDS)) {
    if (words.some((w) => text.includes(w))) {
      return categoryId;
    }
  }
  return "general";
}
